env:
  es2017: true
  browser: true
  jest: true

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module

settings:
  react:
    version: '17'

extends: [
  'htmlacademy/es6',
  'plugin:react/recommended',
  'plugin:react-hooks/recommended',
]

plugins: [
  'react',
  'react-hooks',
]

rules: {
  'react-hooks/rules-of-hooks': 'error',
  'react-hooks/exhaustive-deps': 'warn',
}
